In [1]:
print("Hello World")

Hello World

In [2]:
!pip install -U "langchain[google-genai]"

Collecting langchain[google-genai]
  Downloading langchain-1.2.15-py3-none-any.whl.metadata (5.8 kB)
Collecting langchain-core<2.0.0,>=1.2.10 (from langchain[google-genai])
  Downloading langchain_core-1.2.28-py3-none-any.whl.metadata (4.4 kB)
Collecting langgraph<1.2.0,>=1.1.5 (from langchain[google-genai])
  Downloading langgraph-1.1.6-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain[google-genai]) (2.12.5)
Collecting langchain-google-genai (from langchain[google-genai])
  Downloading langchain_google_genai-4.2.1-py3-none-any.whl.metadata (2.7 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core<2.0.0,>=1.2.10->langchain[google-genai])
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core<2.0.0,>=1.2.10->langchain[google-genai])
  Downloading langsmith-0.7.30-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain[google-genai]) (26.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain[google-genai]) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain[google-genai]) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain[google-genai]) (4.15.0)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.2.10->langchain[google-genai])
  Downloading uuid_utils-0.14.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Collecting langgraph-checkpoint<5.0.0,>=2.1.0 (from langgraph<1.2.0,>=1.1.5->langchain[google-genai])
  Downloading langgraph_checkpoint-4.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.9 (from langgraph<1.2.0,>=1.1.5->langchain[google-genai])
  Downloading langgraph_prebuilt-1.0.9-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.2.0,>=1.1.5->langchain[google-genai])
  Downloading langgraph_sdk-0.3.13-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain[google-genai]) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain[google-genai]) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain[google-genai]) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain[google-genai]) (0.4.2)
Collecting filetype<2.0.0,>=1.2.0 (from langchain-google-genai->langchain[google-genai])
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: google-genai<2.0.0,>=1.56.0 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai->langchain[google-genai]) (1.68.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (0.28.1)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (2.32.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (16.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (1.3.1)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain[google-genai]) (3.1.1)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain[google-genai])
  Downloading ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain[google-genai])
  Downloading orjson-3.11.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 1.4 MB/s eta 0:00:00
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain[google-genai])
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain[google-genai])
  Downloading zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (2.5.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.56.0->langchain-google-genai->langchain[google-genai]) (0.6.3)
Downloading langchain_core-1.2.28-py3-none-any.whl (508 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.7/508.7 kB 13.5 MB/s eta 0:00:0000:01
Downloading langgraph-1.1.6-py3-none-any.whl (169 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.8/169.8 kB 17.0 MB/s eta 0:00:00
Downloading langchain-1.2.15-py3-none-any.whl (112 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.7/112.7 kB 12.1 MB/s eta 0:00:00
Downloading langchain_google_genai-4.2.1-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 6.2 MB/s eta 0:00:00
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langgraph_checkpoint-4.0.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 5.4 MB/s eta 0:00:00
Downloading langgraph_prebuilt-1.0.9-py3-none-any.whl (35 kB)
Downloading langgraph_sdk-0.3.13-py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.7/96.7 kB 9.9 MB/s eta 0:00:00
Downloading langsmith-0.7.30-py3-none-any.whl (372 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 372.7/372.7 kB 34.1 MB/s eta 0:00:00
Downloading uuid_utils-0.14.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.7/345.7 kB 33.2 MB/s eta 0:00:00
Downloading orjson-3.11.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 kB 13.8 MB/s eta 0:00:00
Downloading ormsgpack-1.12.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.6/212.6 kB 17.7 MB/s eta 0:00:00
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 5.2 MB/s eta 0:00:00
Downloading zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 97.7 MB/s eta 0:00:00:00:01
Installing collected packages: filetype, zstandard, uuid-utils, ormsgpack, orjson, jsonpatch, requests-toolbelt, langsmith, langgraph-sdk, langchain-core, langgraph-checkpoint, langchain-google-genai, langgraph-prebuilt, langgraph, langchain
Successfully installed filetype-1.2.0 jsonpatch-1.33 langchain-1.2.15 langchain-core-1.2.28 langchain-google-genai-4.2.1 langgraph-1.1.6 langgraph-checkpoint-4.0.1 langgraph-prebuilt-1.0.9 langgraph-sdk-0.3.13 langsmith-0.7.30 orjson-3.11.8 ormsgpack-1.12.2 requests-toolbelt-1.0.0 uuid-utils-0.14.1 zstandard-0.25.0

In [3]:
import os
import getpass

# Set API key using secure input
api_key = getpass.getpass("Enter your GOOGLE_API_KEY: ")
os.environ["GOOGLE_API_KEY"] = api_key
print(f"API key set: {'*' * len(api_key)}")

API key set:

In [4]:
!pip install -U "langchain-openrouter"

Collecting langchain-openrouter
  Downloading langchain_openrouter-0.2.1-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.23 in /usr/local/lib/python3.12/dist-packages (from langchain-openrouter) (1.2.28)
Collecting openrouter<1.0.0,>=0.7.11 (from langchain-openrouter)
  Downloading openrouter-0.8.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (0.7.30)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (2.12.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (0.14.1)
Requirement already satisfied: httpcore>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from openrouter<1.0.0,>=0.7.11->langchain-openrouter) (1.0.9)
Requirement already satisfied: httpx>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from openrouter<1.0.0,>=0.7.11->langchain-openrouter) (0.28.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpcore>=1.0.9->openrouter<1.0.0,>=0.7.11->langchain-openrouter) (2026.2.25)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore>=1.0.9->openrouter<1.0.0,>=0.7.11->langchain-openrouter) (0.16.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.28.1->openrouter<1.0.0,>=0.7.11->langchain-openrouter) (4.13.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.28.1->openrouter<1.0.0,>=0.7.11->langchain-openrouter) (3.11)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (2.32.4)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.23->langchain-openrouter) (2.5.0)
Downloading langchain_openrouter-0.2.1-py3-none-any.whl (21 kB)
Downloading openrouter-0.8.1-py3-none-any.whl (337 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 337.2/337.2 kB 7.2 MB/s eta 0:00:00a 0:00:01
Installing collected packages: openrouter, langchain-openrouter
Successfully installed langchain-openrouter-0.2.1 openrouter-0.8.1

In [5]:
import os
import getpass

# Set API key using secure input
api_key = getpass.getpass("Enter your OPENROUTER_API_KEY: ")
os.environ["OPENROUTER_API_KEY"] = api_key
print(f"API key set: {'*' * len(api_key)}")

API key set: *************************************************************************

In [6]:
from langchain_openrouter import ChatOpenRouter


model = ChatOpenRouter(model="auto")

In [7]:
static_prompt = "Explain the concept of Sentiment Analysis in under 2 sentences."
response = model.invoke(static_prompt)
print(response)

content=' Sentiment analysis is a natural language processing technique used to identify and extract subjective information from text data, such as opinions, emotions, and attitudes, to understand the emotional tone behind words and determine whether it is positive, negative, or neutral. It is widely used in various applications, including social media monitoring, customer feedback analysis, and market research, to gain insights into public opinion and customer sentiment.' additional_kwargs={} response_metadata={'model_name': 'mistralai/mistral-7b-instruct-v0.1', 'id': 'gen-1775987761-PaxCAIM8uc5sNlDan4qQ', 'created': 1775987761, 'object': 'chat.completion', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'openrouter'} id='lc_run--019d811e-a138-7403-9d4e-9a696de66e85-0' tool_calls=[] invalid_tool_calls=[] usage_metadata={'input_tokens': 22, 'output_tokens': 82, 'total_tokens': 104, 'input_token_details': {'cache_read': 0, 'cache_creation': 0}, 'output_token_details': {'reasoning': 0}}

In [8]:
!pip install langchain

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.15)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.28)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.1.6)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.7.30)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (26.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (1.0.9)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (0.3.13)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.32.4)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (0.25.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.5.0)

In [9]:
from langchain_core.prompts import PromptTemplate

dynamic_prompt_template = PromptTemplate(
    template = "Explain the concept of {topic} in under {length} sentences.",
    input_variables = ["topic", "length"]
)

In [10]:
user_topic=input("Enter a topic: ")
user_length=input("Enter the number of sentences: ")

dynamic_prompt = dynamic_prompt_template.format(topic=user_topic, length=user_length)
print(dynamic_prompt)

Explain the concept of hi in under 1 sentences.

In [11]:
response=model.invoke( dynamic_prompt)
print(response)

content=' "Hi" is a common greeting used to initiate a friendly conversation or interaction, expressing acknowledgement and recognition of the person being addressed.' additional_kwargs={} response_metadata={'model_name': 'mistralai/mistral-7b-instruct-v0.1', 'id': 'gen-1775988087-BxOoTWnj3BzwumV7bgq4', 'created': 1775988087, 'object': 'chat.completion', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'openrouter'} id='lc_run--019d8123-9906-7891-a329-2e984a0d1c62-0' tool_calls=[] invalid_tool_calls=[] usage_metadata={'input_tokens': 19, 'output_tokens': 32, 'total_tokens': 51, 'input_token_details': {'cache_read': 0, 'cache_creation': 0}, 'output_token_details': {'reasoning': 0}}

This video from the **CampusX** YouTube channel is a deep dive into the **Prompts** component of LangChain. It explains why we need specialized prompt templates instead of simple f-strings and covers various types of templates used in production-level LLM applications.

### **Video Summary**
The video focuses on making LLM interactions more dynamic and organized. Key highlights include:
* **The Problem with Simple Strings:** Using standard Python f-strings is difficult to manage as applications scale. LangChain's PromptTemplates provide a structured way to handle inputs and reuse logic [[01:49](http://www.youtube.com/watch?v=3TGqlQxpuU0&t=109)].
* **Prompt Management:** How to create, format, and save prompts to files (JSON or YAML) for better version control.
* **Chat Prompt Templates:** Handling chat-based models (like GPT-4) using `SystemMessage`, `HumanMessage`, and `AIMessage` [[01:16:47](http://www.youtube.com/watch?v=3TGqlQxpuU0&t=4607)].
* **Few-Shot Prompting:** Teaching the LLM by providing examples within the prompt.
* **Message Placeholders:** Managing chat history and dynamic lists of messages efficiently [[01:17:07](http://www.youtube.com/watch?v=3TGqlQxpuU0&t=4627)].

---

### **Core Concepts Taught**

#### **1. Prompt Templates**
Instead of hardcoding instructions, you create a template with placeholders (variables).
* **Why?** It allows you to reuse the "instruction" part while only changing the "data" part.
* **Usage:** You define `input_variables` and a `template` string.


#### **2. ChatPromptTemplate**
LLMs often distinguish between who is speaking. LangChain uses:
* **SystemMessage:** Sets the behavior/persona of the AI (e.g., "You are a helpful travel guide").
* **HumanMessage:** The user's query.
* **AIMessage:** The response from the AI.
* **MessagesPlaceholder:** A special tool to inject a list of messages (like chat history) into a template [[01:17:14](http://www.youtube.com/watch?v=3TGqlQxpuU0&t=4634)].

#### **3. Few-Shot Prompting**
This technique involves giving the model a few examples of input-output pairs so it understands the pattern you want it to follow.
* **Example:** Providing 3 examples of sentiment analysis before asking for the 4th one.

#### **4. Composition & Serialization**
* **PipelinePrompt:** Combining multiple templates into one.
* **Serialization:** Saving your prompts as `.json` or `.yaml` files so you don't clutter your Python code.

---

### **Tasks to Master LangChain Prompts**

To truly learn these concepts, try completing these hands-on tasks:

**Task 1: The Basic Template**
Create a `PromptTemplate` for a "Chef AI."
* Input variable: `cuisine_type`.
* Template: "You are an expert chef. Give me a 3-course menu for {cuisine_type} food."
* **Goal:** Successfully format and print the prompt using `.format(cuisine_type="Italian")`.

**Task 2: Build a Chat Persona**
Use `ChatPromptTemplate` to create a "Sarcastic Technical Support" bot.
* Use a `SystemMessage` to set the tone.
* Use a `HumanMessage` for the user's technical problem.
* **Goal:** Invoke an LLM (like OpenAI or Anthropic) and see if it maintains the sarcastic persona.

**Task 3: Few-Shot Implementation**
Create a prompt that converts "Normal English" to "Shakespearean English."
* Provide 3 examples (e.g., "Hello" -> "Greetings, fair traveler").
* Use the `FewShotPromptTemplate` class.
* **Goal:** Get the model to convert a new sentence accurately based on your examples.

**Task 4: Chat History with Placeholders**
Simulate a conversation where the AI remembers the user's name.
* Use `MessagesPlaceholder(variable_name="history")`.
* Pass a list of previous messages (Human/AI) into the template.
* **Goal:** Ask "What is my name?" after telling the AI your name in a previous message [[01:16:54](http://www.youtube.com/watch?v=3TGqlQxpuU0&t=4614)].

You can watch the full video here: [Prompts in LangChain | CampusX](https://www.youtube.com/watch?v=3TGqlQxpuU0)


http://googleusercontent.com/youtube_content/0

In [12]:
# Cusine Type
from langchain_core.prompts import PromptTemplate

prompt_template = PromptTemplate(
    template = "You are an expert chef. Give me a 3-course menu for {cuisine_type} food.",
    input_variables = ["cuisine_type"]
)

print(prompt_template.format(cuisine_type="Italian"))

You are an expert chef. Give me a 3-course menu for Italian food.

In [13]:
cuisine_prompt = PromptTemplate(
    template = "You are an expert chef. Give me a 3-course menu for {cuisine_type} food.",
    input_variables = ["cuisine_type"]
)

print(cuisine_prompt.format(cuisine_type="Italian"))

You are an expert chef. Give me a 3-course menu for Italian food.

In [14]:
cussine_response=model.invoke(cussine_prompt.format(cuisine_type="Italian"))
print(cussine_response)

NameError: name 'cussine_prompt' is not defined

In [ ]:
# messages 
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage

In [ ]:
messages = [
    SystemMessage(content="You are a helpful assistant."),
    HumanMessage(content="Hello, how are you?"),
    AIMessage(content="I'm doing well, thanks!"),
    HumanMessage(content="What is your name?")
]

print(messages)

[SystemMessage(content='You are a helpful assistant.', additional_kwargs={}, response_metadata={}), HumanMessage(content='Hello, how are you?', additional_kwargs={}, response_metadata={}), AIMessage(content="I'm doing well, thanks!", additional_kwargs={}, response_metadata={}, tool_calls=[], invalid_tool_calls=[]), HumanMessage(content='What is your name?', additional_kwargs={}, response_metadata={})]

In [ ]:
message_result=model.invoke(messages)
print(message_result)

content=" I don't have a name. I'm here to help answer any questions you have to the best of my ability. How can I assist you today?" additional_kwargs={} response_metadata={'model_name': 'mistralai/mistral-7b-instruct-v0.1', 'id': 'gen-1775985373-aj2Glfk186sjCR5AhHsM', 'created': 1775985373, 'object': 'chat.completion', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'openrouter'} id='lc_run--019d80fa-2fc9-74b3-9e86-4c1d83420c0a-0' tool_calls=[] invalid_tool_calls=[] usage_metadata={'input_tokens': 33, 'output_tokens': 34, 'total_tokens': 67, 'input_token_details': {'cache_read': 0, 'cache_creation': 0}, 'output_token_details': {'reasoning': 0}}

In [ ]:
messages = [
    {"role": "system", "content": "You are a poetry expert"},
    {"role": "user", "content": "Write a haiku about spring"},
    {"role": "assistant", "content": "Cherry blossoms bloom..."}
]
response = model.invoke(messages)

In [ ]:
response

AIMessage(content=" Life awakens, swift:\n\nCherry blossoms bloom,\nSoft petals dance in breeze,\nSpring's gentle, fleeting grace.", additional_kwargs={}, response_metadata={'model_name': 'mistralai/mistral-7b-instruct-v0.1', 'id': 'gen-1775985394-YppYAJPsiN5YGgPWGCRV', 'created': 1775985394, 'object': 'chat.completion', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'openrouter'}, id='lc_run--019d80fa-8143-7341-ae22-cdeed2e477ed-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 28, 'output_tokens': 37, 'total_tokens': 65, 'input_token_details': {'cache_read': 0, 'cache_creation': 0}, 'output_token_details': {'reasoning': 0}})


Message types
 System message - Tells the model how to behave and provide context for interactions
 Human message - Represents user input and interactions with the model
 AI message - Responses generated by the model, including text content, tool calls, and metadata
 Tool message - Represents the outputs of tool calls
​

In [ ]:
system_msg = SystemMessage("You are a helpful coding assistant.")

messages = [
    system_msg,
    HumanMessage("How do I create a REST API?")
]
response = model.invoke(messages)

In [ ]:
print(response)

content='Creating a REST (Representational State Transfer) API is a common way to expose data and functionality over HTTP so that clients—like web browsers, mobile apps, or other services—can interact with your system in a language‑agnostic, stateless manner. Below is a practical, end‑to‑end guide that walks you through the key decisions, the basic architecture, and a concrete example in two popular stacks (Python\u202f/\u202fFlask and Node.js\u202f/\u202fExpress). Feel free to pick the language/framework that best fits your project.\n\n---\n\n## 1. High‑Level Overview\n\n| Step | What you’ll do | Why it matters |\n|------|----------------|----------------|\n| **Define the domain** | Identify the resources (e.g., `users`, `orders`, `products`) and the actions clients need (CRUD). | Gives you a clear contract (API spec) that developers can rely on. |\n| **Design the API contract** | Draft endpoints, HTTP methods, request/response payloads, status codes, and authentication. Use OpenAPI (Swagger) or API Blueprint to document. | Guarantees consistency, makes onboarding easier, and enables automated tooling. |\n| **Choose a tech stack** | Select language, framework, database, and hosting environment. | Influences development speed, performance, and ecosystem support. |\n| **Set up the project** | Scaffold the project, configure dependencies, and establish a directory layout. | Keeps the codebase organized and maintainable. |\n| **Implement endpoints** | Write the logic that maps HTTP requests to business operations (validation, persistence, etc.). | Core functionality of your API. |\n| **Add middleware** | Logging, error handling, CORS, rate limiting, authentication (JWT, OAuth2), etc. | Improves security, observability, and developer experience. |\n| **Write tests** | Unit tests for business logic, integration tests for endpoint behavior, and optionally contract tests. | Ensures reliability and eases future changes. |\n| **Document & version** | Publish the OpenAPI spec, generate client SDKs if desired, and version your API (e.g., `/v1/`). | Makes the API consumer‑friendly and future‑proof. |\n| **Deploy & monitor** | Deploy to a serverless platform, containers, or VMs; set up health checks, log aggregation, and metrics. | Guarantees availability and lets you react to issues quickly. |\n\n---\n\n## 2. Planning Your API – Example Domain\n\nLet’s imagine a simple **Task Management** service. The main resource is a **Task**.\n\n| Resource | Attributes | Example |\n|----------|------------|---------|\n| `Task` | `id` (UUID), `title` (string), `description` (string), `completed` (bool), `created_at` (timestamp) | `{ "id":"123e...", "title":"Buy milk", "description":"2% skim", "completed":false, "created_at":"2024-01-01T12:00:00Z" }` |\n\n### Suggested Endpoints (CRUD)\n\n| Method | URL | Description |\n|--------|-----|-------------|\n| `GET` | `/api/v1/tasks` | List all tasks (support pagination & filters). |\n| `POST` | `/api/v1/tasks` | Create a new task. |\n| `GET` | `/api/v1/tasks/{id}` | Retrieve a single task. |\n| `PUT` | `/api/v1/tasks/{id}` | Replace a task (full update). |\n| `PATCH` | `/api/v1/tasks/{id}` | Partial update (e.g., mark completed). |\n| `DELETE` | `/api/v1/tasks/{id}` | Delete a task. |\n\n**Common response status codes**\n\n| Code | Meaning | Typical use |\n|------|----------|-------------|\n| 200 | OK | Successful `GET` or `PUT`. |\n| 201 | Created | Successful `POST` (return `Location` header). |\n| 204 | No Content | Successful `DELETE` (no body). |\n| 400 | Bad Request | Validation error. |\n| 401 | Unauthorized | Missing or invalid auth token. |\n| 403 | Forbidden | Authenticated but not authorized. |\n| 404 | Not Found | Resource does not exist. |\n| 409 | Conflict | Duplicate resource, e.g., unique title. |\n| 500 | Internal Server Error | Unexpected server failure. |\n\n**Authentication** – For a public API you might start with **JWT** (JSON Web Tokens) passed in the `Authorization: Bearer <token>` header. Later you could add OAuth2 or API‑key schemes.\n\n---\n\n## 3. Implementation Walkthrough\n\nBelow are two ready‑to‑run minimal examples that cover all the CRUD endpoints and basic error handling. Feel free to expand them with validation libraries, ORM models, and more sophisticated middleware.\n\n> **Tip:** Even though the examples are tiny, keep the same folder structure in a real project. That will make future growth easier.\n\n---\n\n### 3.1. Python + Flask (with Flask‑RESTful & SQLAlchemy)\n\n#### 3.1.1. Prerequisites\n\n```bash\n# Create a virtual environment (optional but recommended)\npython -m venv venv\nsource venv/bin/activate   # on Windows: venv\\Scripts\\activate\n\n# Install dependencies\npip install Flask Flask-RESTful Flask-SQLAlchemy marshmallow marshmallow-sqlalchemy python-dotenv\n```\n\n#### 3.1.2. Project Layout\n\n```\ntaskapi/\n├─ app.py\n├─ models.py\n├─ schemas.py\n├─ resources.py\n├─ config.py\n└─ .env\n```\n\n#### 3.1.3. Source Files\n\n**`config.py`**\n\n```python\nimport os\nfrom dotenv import load_dotenv\n\nload_dotenv()  # reads .env file\n\nclass Config:\n    SQLALCHEMY_DATABASE_URI = os.getenv(\'DATABASE_URL\', \'sqlite:///tasks.db\')\n    SQLALCHEMY_TRACK_MODIFICATIONS = False\n    SECRET_KEY = os.getenv(\'SECRET_KEY\', \'super-secret\')\n```\n\n**`models.py`**\n\n```python\nimport uuid\nfrom datetime import datetime\nfrom flask_sqlalchemy import SQLAlchemy\n\ndb = SQLAlchemy()\n\ndef generate_uuid():\n    return str(uuid.uuid4())\n\nclass Task(db.Model):\n    __tablename__ = \'tasks\'\n\n    id = db.Column(db.String, primary_key=True, default=generate_uuid)\n    title = db.Column(db.String(200), nullable=False)\n    description = db.Column(db.Text, nullable=True)\n    completed = db.Column(db.Boolean, default=False)\n    created_at = db.Column(db.DateTime, default=datetime.utcnow)\n\n    def __repr__(self):\n        return f"<Task {self.id} {self.title}>"\n```\n\n**`schemas.py`** (Marshmallow for (de)serialization & validation)\n\n```python\nfrom marshmallow import Schema, fields, validate\n\nclass TaskSchema(Schema):\n    id = fields.Str(dump_only=True)\n    title = fields.Str(required=True, validate=validate.Length(min=1, max=200))\n    description = fields.Str(allow_none=True)\n    completed = fields.Boolean()\n    created_at = fields.DateTime(dump_only=True)\n```\n\n**`resources.py`** (Flask‑RESTful resources)\n\n```python\nfrom flask import request\nfrom flask_restful import Resource\nfrom models import db, Task\nfrom schemas import TaskSchema\n\ntask_schema = TaskSchema()\ntasks_schema = TaskSchema(many=True)\n\nclass TaskListResource(Resource):\n    def get(self):\n        """List all tasks (supports optional pagination via query params)."""\n        # Simple pagination: ?page=1&per_page=10\n        page = request.args.get(\'page\', 1, type=int)\n        per_page = request.args.get(\'per_page\', 20, type=int)\n\n        pagination = Task.query.paginate(page=page, per_page=per_page, error_out=False)\n        result = tasks_schema.dump(pagination.items)\n\n        return {\n            "tasks": result,\n            "total": pagination.total,\n            "page": pagination.page,\n            "pages": pagination.pages,\n        }, 200\n\n    def post(self):\n        """Create a new task."""\n        json_data = request.get_json()\n        if not json_data:\n            return {"message": "No input data provided"}, 400\n\n        # Validate & deserialize\n        try:\n            data = task_schema.load(json_data)\n        except Exception as err:\n            return {"message": "Validation error", "errors": err.messages}, 400\n\n        # Persist\n        task = Task(**data)\n        db.session.add(task)\n        db.session.commit()\n\n        return task_schema.dump(task), 201\n\n\nclass TaskResource(Resource):\n    def get(self, task_id):\n        task = Task.query.get_or_404(task_id)\n        return task_schema.dump(task), 200\n\n    def put(self, task_id):\n        """Full replace of a task."""\n        task = Task.query.get_or_404(task_id)\n        json_data = request.get_json()\n        if not json_data:\n            return {"message": "No input data provided"}, 400\n\n        try:\n            data = task_schema.load(json_data)\n        except Exception as err:\n            return {"message": "Validation error", "errors": err.messages}, 400\n\n        # Update all fields\n        task.title = data[\'title\']\n        task.description = data.get(\'description\')\n        task.completed = data.get(\'completed\', False)\n\n        db.session.commit()\n        return task_schema.dump(task), 200\n\n    def patch(self, task_id):\n        """Partial update."""\n        task = Task.query.get_or_404(task_id)\n        json_data = request.get_json()\n        if not json_data:\n            return {"message": "No input data provided"}, 400\n\n        # Only validate fields present\n        try:\n            data = task_schema.load(json_data, partial=True)\n        except Exception as err:\n            return {"message": "Validation error", "errors": err.messages}, 400\n\n        for key, value in data.items():\n            setattr(task, key, value)\n\n        db.session.commit()\n        return task_schema.dump(task), 200\n\n    def delete(self, task_id):\n        task = Task.query.get_or_404(task_id)\n        db.session.delete(task)\n        db.session.commit()\n        return "", 204\n```\n\n**`app.py`** (Application bootstrap)\n\n```python\nfrom flask import Flask\nfrom flask_restful import Api\nfrom config import Config\nfrom models import db, Task\nfrom resources import TaskListResource, TaskResource\n\ndef create_app():\n    app = Flask(__name__)\n    app.config.from_object(Config)\n\n    # Initialize extensions\n    db.init_app(app)\n\n    api = Api(app, prefix=\'/api/v1\')\n\n    # Register routes\n    api.add_resource(TaskListResource, \'/tasks\')\n    api.add_resource(TaskResource, \'/tasks/<string:task_id>\')\n\n    @app.before_first_request\n    def create_tables():\n        db.create_all()\n\n    # Simple health check\n    @app.route(\'/health\')\n    def health():\n        return {"status": "ok"}, 200\n\n    return app\n\nif __name__ == \'__main__\':\n    app = create_app()\n    app.run(debug=True)  # Set debug=False in production!\n```\n\n**`.env`** (optional – keep secret values out of source control)\n\n```\nDATABASE_URL=sqlite:///tasks.db\nSECRET_KEY=replace-with-a-strong-random-string\n```\n\n#### 3.1.4. Running the API\n\n```bash\nexport FLASK_APP=app.py   # on Windows: set FLASK_APP=app.py\nflask run\n```\n\nThe API will be reachable at `http://127.0.0.1:5000/api/v1/tasks`. You can test it quickly with `curl` or a tool like **Postman** / **Insomnia**.\n\n**Example using curl:**\n\n```bash\n# Create a task\ncurl -X POST http://127.0.0.1:5000/api/v1/tasks \\\n     -H "Content-Type: application/json" \\\n     -d \'{"title": "Buy groceries", "description": "Milk, eggs, bread"}\'\n\n# List tasks\ncurl http://127.0.0.1:5000/api/v1/tasks\n\n# Get a single task (replace <id>)\ncurl http://127.0.0.1:5000/api/v1/tasks/<id>\n\n# Mark as completed (PATCH)\ncurl -X PATCH http://127.0.0.1:5000/api/v1/tasks/<id> \\\n     -H "Content-Type: application/json" \\\n     -d \'{"completed": true}\'\n```\n\n---\n\n### 3.2. Node.js + Express (with Sequelize)\n\n#### 3.2.1. Prerequisites\n\n```bash\n# Using npm or yarn – create a new directory first\nmkdir taskapi-node && cd taskapi-node\nnpm init -y\n\n# Install dependencies\nnpm install express sequelize sqlite3 dotenv cors morgan\nnpm install --save-dev nodemon\n```\n\nOptionally, for validation you can add **joi**:\n\n```bash\nnpm install joi\n```\n\n#### 3.2.2. Project Layout\n\n```\ntaskapi-node/\n├─ src/\n│  ├─ config/\n│  │   └─ db.js\n│  ├─ models/\n│  │   └─ task.js\n│  ├─ routes/\n│  │   └─ tasks.js\n│  ├─ middlewares/\n│  │   ├─ errorHandler.js\n│  │   └─ asyncHandler.js\n│  ├─ app.js\n│  └─ server.js\n├─ .env\n└─ package.json\n```\n\n#### 3.2.3. Source Files\n\n**`src/config/db.js`**\n\n```js\nrequire(\'dotenv\').config();\nconst { Sequelize } = require(\'sequelize\');\n\nconst sequelize = new Sequelize({\n  dialect: \'sqlite\',\n  storage: process.env.DB_PATH || \'database.sqlite\',\n  logging: false, // set true for SQL debugging\n});\n\nmodule.exports = sequelize;\n```\n\n**`src/models/task.js`**\n\n```js\nconst { DataTypes } = require(\'sequelize\');\nconst sequelize = require(\'../config/db\');\n\nconst Task = sequelize.define(\'Task\', {\n  id: {\n    type: DataTypes.UUID,\n    defaultValue: DataTypes.UUIDV4,\n    primaryKey: true,\n  },\n  title: {\n    type: DataTypes.STRING(200),\n    allowNull: false,\n  },\n  description: {\n    type: DataTypes.TEXT,\n  },\n  completed: {\n    type: DataTypes.BOOLEAN,\n    defaultValue: false,\n  },\n}, {\n  timestamps: true, // adds createdAt and updatedAt\n  tableName: \'tasks\',\n});\n\nmodule.exports = Task;\n```\n\n**`src/middlewares/asyncHandler.js`** (helper to catch async errors)\n\n```js\nmodule.exports = fn => (req, res, next) => {\n  Promise.resolve(fn(req, res, next)).catch(next);\n};\n```\n\n**`src/middlewares/errorHandler.js`**\n\n```js\nmodule.exports = (err, req, res, next) => {\n  console.error(err); // In production use a proper logger\n  const status = err.status || 500;\n  res.status(status).json({ message: err.message || \'Internal Server Error\' });\n};\n```\n\n**`src/routes/tasks.js`**\n\n```js\nconst express = require(\'express\');\nconst router = express.Router();\nconst Task = require(\'../models/task\');\nconst asyncHandler = require(\'../middlewares/asyncHandler\');\nconst Joi = require(\'joi\');\n\n// Validation schema with Joi\nconst taskSchema = Joi.object({\n  title: Joi.string().max(200).required(),\n  description: Joi.string().allow(\'\', null),\n  completed: Joi.boolean(),\n});\n\n// ---------- LIST ----------\nrouter.get(\'/\', asyncHandler(async (req, res) => {\n  const { page = 1, limit = 20 } = req.query;\n  const offset = (page - 1) * limit;\n\n  const { rows, count } = await Task.findAndCountAll({\n    limit: Number(limit),\n    offset: Number(offset),\n    order: [[\'createdAt\', \'DESC\']],\n  });\n\n  res.json({\n    tasks: rows,\n    total: count,\n    page: Number(page),\n    pages: Math.ceil(count / limit),\n  });\n}));\n\n// ---------- CREATE ----------\nrouter.post(\'/\', asyncHandler(async (req, res) => {\n  const { error, value } = taskSchema.validate(req.body);\n  if (error) return res.status(400).json({ message: error.message });\n\n  const task = await Task.create(value);\n  res.status(201).json(task);\n}));\n\n// ---------- READ ----------\nrouter.get(\'/:id\', asyncHandler(async (req, res) => {\n  const task = await Task.findByPk(req.params.id);\n  if (!task) return res.status(404).json({ message: \'Task not found\' });\n  res.json(task);\n}));\n\n// ---------- REPLACE ----------\nrouter.put(\'/:id\', asyncHandler(async (req, res) => {\n  const { error, value } = taskSchema.validate(req.body);\n  if (error) return res.status(400).json({ message: error.message });\n\n  const task = await Task.findByPk(req.params.id);\n  if (!task) return res.status(404).json({ message: \'Task not found\' });\n\n  await task.update(value);\n  res.json(task);\n}));\n\n// ---------- PATCH ----------\nrouter.patch(\'/:id\', asyncHandler(async (req, res) => {\n  const { error, value } = taskSchema.validate(req.body, { presence: \'optional\' });\n  if (error) return res.status(400).json({ message: error.message });\n\n  const task = await Task.findByPk(req.params.id);\n  if (!task) return res.status(404).json({ message: \'Task not found\' });\n\n  await task.update(value);\n  res.json(task);\n}));\n\n// ---------- DELETE ----------\nrouter.delete(\'/:id\', asyncHandler(async (req, res) => {\n  const task = await Task.findByPk(req.params.id);\n  if (!task) return res.status(404).json({ message: \'Task not found\' });\n\n  await task.destroy();\n  res.status(204).send();\n}));\n\nmodule.exports = router;\n```\n\n**`src/app.js`**\n\n```js\nconst express = require(\'express\');\nconst cors = require(\'cors\');\nconst morgan = require(\'morgan\');\nconst taskRoutes = require(\'./routes/tasks\');\nconst errorHandler = require(\'./middlewares/errorHandler\');\n\nrequire(\'dotenv\').config();\n\nconst app = express();\n\n// Global middlewares\napp.use(cors());                 // enable CORS for all origins (tighten in prod)\napp.use(morgan(\'dev\'));          // request logging\napp.use(express.json());         // parse JSON bodies\n\n// Health check endpoint\napp.get(\'/health\', (req, res) => res.json({ status: \'ok\' }));\n\n// API routes (prefix with version)\napp.use(\'/api/v1/tasks\', taskRoutes);\n\n// Centralized error handling\napp.use(errorHandler);\n\nmodule.exports = app;\n```\n\n**`src/server.js`**\n\n```js\nconst app = require(\'./app\');\nconst sequelize = require(\'./config/db\');\n\nconst PORT = process.env.PORT || 3000;\n\n// Sync DB then start server\nsequelize.sync({ alter: true })   // use { force: true } only for dev resets\n  .then(() => {\n    console.log(\'Database synced\');\n    app.listen(PORT, () => {\n      console.log(`🚀 Server listening on http://localhost:${PORT}`);\n    });\n  })\n  .catch(err => {\n    console.error(\'Failed to sync database:\', err);\n  });\n```\n\n**`.env`**\n\n```\nPORT=3000\nDB_PATH=database.sqlite\n```\n\n#### 3.2.4. Running the API\n\nAdd a development script to `package.json`:\n\n```json\n{\n  "scripts": {\n    "dev": "nodemon src/server.js"\n  }\n}\n```\n\nThen start it:\n\n```bash\nnpm run dev\n```\n\nYour CRUD endpoints are now reachable under `http://localhost:3000/api/v1/tasks`. Use `curl`, Postman, or any HTTP client to interact.\n\n**Sample `curl` requests**\n\n```bash\n# Create a task\ncurl -X POST http://localhost:3000/api/v1/tasks \\\n     -H "Content-Type: application/json" \\\n     -d \'{"title":"Write docs","description":"Add OpenAPI spec"}\'\n\n# List tasks\ncurl http://localhost:3000/api/v1/tasks\n\n# Update (PUT)\ncurl -X PUT http://localhost:3000/api/v1/tasks/<id> \\\n     -H "Content-Type: application/json" \\\n     -d \'{"title":"Write API docs","completed":false}\'\n\n# Partial update (PATCH)\ncurl -X PATCH http://localhost:3000/api/v1/tasks/<id> \\\n     -H "Content-Type: application/json" \\\n     -d \'{"completed":true}\'\n\n# Delete\ncurl -X DELETE http://localhost:3000/api/v1/tasks/<id>\n```\n\n---\n\n## 4. Bonus: Auto‑Generating Docs with OpenAPI (Swagger)\n\nBoth stacks can serve a JSON/YAML OpenAPI spec that tools like **Swagger UI**, **Redoc**, or **Postman** can render automatically.\n\n### 4.1. Flask example (using `flask-smorest`)\n\n```bash\npip install flask-smorest\n```\n\nThen wrap your resources:\n\n```python\nfrom flask_smorest import Blueprint, Api\n\napi = Api(app)\nblp = Blueprint(\'tasks\', \'tasks\', url_prefix=\'/tasks\', description=\'Task operations\')\n\n@blp.route(\'/\')\nclass Tasks(Resource):\n    @blp.response(200, tasks_schema)\n    def get(self):\n        ...\n```\n\nRunning the app will expose `/swagger.json` and `/docs` (Swagger UI).\n\n### 4.2. Express example (using `swagger-jsdoc` + `swagger-ui-express`)\n\n```bash\nnpm install swagger-jsdoc swagger-ui-express\n```\n\nCreate `src/swagger.js`:\n\n```js\nconst swaggerJsdoc = require(\'swagger-jsdoc\');\nconst swaggerUi = require(\'swagger-ui-express\');\n\nconst options = {\n  definition: {\n    openapi: \'3.0.0\',\n    info: {\n      title: \'Task API\',\n      version: \'1.0.0\',\n    },\n  },\n  apis: [\'./src/routes/*.js\'], // <-- JSDoc comments will be read from here\n};\n\nconst specs = swaggerJsdoc(options);\nmodule.exports = (app) => {\n  app.use(\'/api-docs\', swaggerUi.serve, swaggerUi.setup(specs));\n};\n```\n\nAdd JSDoc comments to your route file (see swagger-jsdoc docs for exact syntax). Then in `app.js`:\n\n```js\nconst setupSwagger = require(\'./swagger\');\nsetupSwagger(app);\n```\n\nNow `http://localhost:3000/api-docs` shows interactive documen

In [ ]:
from langchain.messages import SystemMessage, HumanMessage

system_msg = SystemMessage("""
You are a senior Python developer with expertise in web frameworks.
Always provide code examples and explain your reasoning.
Be concise but thorough in your explanations.
""")

messages = [
    system_msg,
    HumanMessage("How do I create a REST API?")
]
response = model.invoke(messages)
print(response)

content='Below is a **step‑by‑step guide** to building a production‑ready REST API in Python.  \nI’ll use **FastAPI** (the current de‑facto standard for modern Python APIs) because it gives you:\n\n* **Automatic OpenAPI/Swagger docs**  \n* **Pydantic‑based data validation** (type‑safe request/response bodies)  \n* **Async‑first design** (great for I/O‑bound workloads)  \n* **Fast performance** (≈\u202fNode/Go‑level)  \n\nIf you prefer Flask, Django‑REST‑Framework, or another stack, the concepts are the same; I’ll note the equivalents at the end.\n\n---\n\n## 1️⃣ Project layout\n\n```\nmy_api/\n├─ app/\n│   ├─ __init__.py\n│   ├─ main.py           # FastAPI app entry‑point\n│   ├─ models.py         # Pydantic schemas + (optional) ORM models\n│   ├─ crud.py           # Data‑access layer (SQLAlchemy queries, etc.)\n│   └─ routers/\n│        ├─ __init__.py\n│        └─ users.py     # Example endpoint group\n├─ tests/\n│   └─ test_users.py\n├─ alembic/               # optional: DB migrations\n├─ .env                   # environment variables\n├─ requirements.txt\n└─ README.md\n```\n\n*Why this structure?*  \nKeeping the **router** files separate from the core app makes it trivial to add versioning or mount sub‑applications later.\n\n---\n\n## 2️⃣ Install the core dependencies\n\n```bash\n# Create a virtualenv (optional but recommended)\npython -m venv .venv\nsource .venv/bin/activate   # Windows: .venv\\Scripts\\activate\n\n# Install FastAPI, an ASGI server, and a DB/ORM of your choice\npip install fastapi[all]      # includes "uvicorn", "pydantic", "email-validator"\npip install sqlalchemy[asyncio]   # async SQLAlchemy 2.x\npip install alembic                # migrations (optional)\npip install python-dotenv          # .env handling\npip install pytest httpx           # testing\n```\n\n`requirements.txt` (generated with `pip freeze > requirements.txt`) could look like:\n\n```\nfastapi[all]==0.110.0\nuvicorn[standard]==0.30.0\nSQLAlchemy[asyncio]==2.0.30\nalembic==1.13.2\npython-dotenv==1.0.1\npydantic==2.7.1\npytest==8.2.0\nhttpx==0.27.0\n```\n\n---\n\n## 3️⃣ Define Pydantic models (schemas)\n\n`app/models.py`\n\n```python\nfrom __future__ import annotations\nfrom typing import Optional\nfrom pydantic import BaseModel, EmailStr, Field\n\n# ---- Request payloads -------------------------------------------------\nclass UserCreate(BaseModel):\n    email: EmailStr\n    full_name: str = Field(..., min_length=1, max_length=100)\n    password: str = Field(..., min_length=8)\n\nclass UserUpdate(BaseModel):\n    full_name: Optional[str] = Field(None, min_length=1, max_length=100)\n    password: Optional[str] = Field(None, min_length=8)\n\n# ---- Response payloads ------------------------------------------------\nclass UserRead(BaseModel):\n    id: int\n    email: EmailStr\n    full_name: str\n\n    class Config:\n        orm_mode = True  # lets FastAPI convert from ORM objects automatically\n```\n\n> **Tip:** Keep separate *Create/Update* vs *Read* schemas. The read model should never expose passwords or internal flags.\n\n---\n\n## 4️⃣ Asynchronous DB layer (SQLAlchemy 2.x)\n\n`app/crud.py`\n\n```python\nfrom sqlalchemy import select, insert, update, delete\nfrom sqlalchemy.ext.asyncio import AsyncSession\nfrom .models import UserCreate, UserRead\nfrom .database import user_table  # defined in app/database.py\n\n# Helper to hash passwords (use passlib or bcrypt in real code)\ndef _hash_pw(pw: str) -> str:\n    import hashlib\n    return hashlib.sha256(pw.encode()).hexdigest()\n\n# ----------------- CREATE -----------------\nasync def create_user(db: AsyncSession, payload: UserCreate) -> UserRead:\n    stmt = insert(user_table).values(\n        email=payload.email,\n        full_name=payload.full_name,\n        password_hash=_hash_pw(payload.password)\n    ).returning(user_table.c.id,\n                user_table.c.email,\n                user_table.c.full_name)\n    result = await db.execute(stmt)\n    await db.commit()\n    return UserRead.model_validate(result.fetchone())\n\n# ----------------- READ (single) -----------------\nasync def get_user(db: AsyncSession, user_id: int) -> UserRead | None:\n    stmt = select(user_table).where(user_table.c.id == user_id)\n    result = await db.execute(stmt)\n    row = result.fetchone()\n    return UserRead.model_validate(row) if row else None\n\n# ----------------- UPDATE -----------------\nasync def update_user(\n    db: AsyncSession,\n    user_id: int,\n    payload: UserUpdate\n) -> UserRead | None:\n    update_vals = {}\n    if payload.full_name is not None:\n        update_vals["full_name"] = payload.full_name\n    if payload.password is not None:\n        update_vals["password_hash"] = _hash_pw(payload.password)\n\n    if not update_vals:\n        return await get_user(db, user_id)\n\n    stmt = (\n        update(user_table)\n        .where(user_table.c.id == user_id)\n        .values(**update_vals)\n        .returning(user_table.c.id, user_table.c.email, user_table.c.full_name)\n    )\n    result = await db.execute(stmt)\n    await db.commit()\n    row = result.fetchone()\n    return UserRead.model_validate(row) if row else None\n\n# ----------------- DELETE -----------------\nasync def delete_user(db: AsyncSession, user_id: int) -> bool:\n    stmt = delete(user_table).where(user_table.c.id == user_id)\n    result = await db.execute(stmt)\n    await db.commit()\n    return result.rowcount > 0\n```\n\n`app/database.py`\n\n```python\nimport os\nfrom sqlalchemy.ext.asyncio import create_async_engine, AsyncSession\nfrom sqlalchemy.orm import sessionmaker, declarative_base\nfrom sqlalchemy import MetaData, Table, Column, Integer, String\n\nDATABASE_URL = os.getenv(\n    "DATABASE_URL",\n    "sqlite+aiosqlite:///./dev.db"   # simple file SQLite for dev\n)\n\nengine = create_async_engine(DATABASE_URL, echo=False, future=True)\n\nAsyncSessionLocal = sessionmaker(\n    bind=engine,\n    class_=AsyncSession,\n    expire_on_commit=False,\n    autoflush=False,\n    autocommit=False,\n)\n\nBase = declarative_base()\n\n# Declarative table definition (you could also use pure Table objects)\nmetadata = MetaData()\n\nuser_table = Table(\n    "users",\n    metadata,\n    Column("id", Integer, primary_key=True),\n    Column("email", String, unique=True, nullable=False),\n    Column("full_name", String, nullable=False),\n    Column("password_hash", String, nullable=False),\n)\n\n# Run this once (or use Alembic) to create tables\nasync def init_db():\n    async with engine.begin() as conn:\n        await conn.run_sync(metadata.create_all)\n```\n\n> **Why async DB?**  \nFastAPI runs on an ASGI server (Uvicorn/Hypercorn). If you block the event loop with a sync driver, you lose the concurrency benefits. Most modern DB drivers have async APIs (`aiosqlite`, `asyncpg`, `mysql-async`, etc.)\n\n---\n\n## 5️⃣ Build routers (endpoint definitions)\n\n`app/routers/users.py`\n\n```python\nfrom fastapi import APIRouter, Depends, HTTPException, status\nfrom sqlalchemy.ext.asyncio import AsyncSession\nfrom .. import crud, models, database\n\nrouter = APIRouter(prefix="/users", tags=["users"])\n\n# Dependency that yields a DB session per request\nasync def get_db() -> AsyncSession:\n    async with database.AsyncSessionLocal() as session:\n        yield session\n\n# ---- CREATE ---------------------------------------------------------\n@router.post(\n    "/",\n    response_model=models.UserRead,\n    status_code=status.HTTP_201_CREATED,\n    summary="Create a new user"\n)\nasync def create_user(\n    payload: models.UserCreate,\n    db: AsyncSession = Depends(get_db)\n):\n    # Simple duplicate‑email guard\n    existing = await crud.get_user_by_email(db, payload.email)\n    if existing:\n        raise HTTPException(\n            status_code=status.HTTP_409_CONFLICT,\n            detail="Email already registered"\n        )\n    return await crud.create_user(db, payload)\n\n# ---- READ (list) -----------------------------------------------------\n@router.get("/", response_model=list[models.UserRead], summary="List all users")\nasync def list_users(db: AsyncSession = Depends(get_db)):\n    stmt = select(database.user_table)\n    result = await db.execute(stmt)\n    rows = result.fetchall()\n    return [models.UserRead.model_validate(row) for row in rows]\n\n# ---- READ (single) ---------------------------------------------------\n@router.get("/{user_id}", response_model=models.UserRead, summary="Get a user")\nasync def read_user(user_id: int, db: AsyncSession = Depends(get_db)):\n    user = await crud.get_user(db, user_id)\n    if not user:\n        raise HTTPException(status_code=404, detail="User not found")\n    return user\n\n# ---- UPDATE ---------------------------------------------------------\n@router.patch("/{user_id}", response_model=models.UserRead)\nasync def update_user(\n    user_id: int,\n    payload: models.UserUpdate,\n    db: AsyncSession = Depends(get_db)\n):\n    user = await crud.update_user(db, user_id, payload)\n    if not user:\n        raise HTTPException(status_code=404, detail="User not found")\n    return user\n\n# ---- DELETE ---------------------------------------------------------\n@router.delete("/{user_id}", status_code=status.HTTP_204_NO_CONTENT)\nasync def delete_user(user_id: int, db: AsyncSession = Depends(get_db)):\n    success = await crud.delete_user(db, user_id)\n    if not success:\n        raise HTTPException(status_code=404, detail="User not found")\n    return None\n```\n\n> **Note:**  \n`crud.get_user_by_email` would be a tiny helper similar to `get_user`; omitted for brevity.\n\n---\n\n## 6️⃣ Assemble the FastAPI application\n\n`app/main.py`\n\n```python\nfrom fastapi import FastAPI\nfrom .routers import users\nfrom . import database\n\napp = FastAPI(\n    title="My Awesome API",\n    version="0.1.0",\n    description="A tiny example demonstrating a production‑ready REST API."\n)\n\n# Mount routers (you could also version them: /v1/users, /v2/users)\napp.include_router(users.router)\n\n# Run DB init on startup (only for dev; in prod use Alembic migrations)\n@app.on_event("startup")\nasync def on_startup():\n    await database.init_db()\n```\n\nRun it locally:\n\n```bash\nuvicorn app.main:app --reload   # --reload for dev auto‑reload\n```\n\nVisit `http://127.0.0.1:8000/docs` → Swagger UI automatically generated from the type hints.\n\n---\n\n## 7️⃣ Testing (pytest + httpx)\n\n`tests/test_users.py`\n\n```python\nimport pytest\nfrom httpx import AsyncClient\nfrom app.main import app\nfrom app import database\n\n@pytest.fixture(scope="module")\nasync def async_client():\n    async with AsyncClient(app=app, base_url="http://testserver") as client:\n        # Ensure fresh DB for the test module\n        async with database.engine.begin() as conn:\n            await conn.run_sync(database.metadata.drop_all)\n            await conn.run_sync(database.metadata.create_all)\n        yield client\n\n@pytest.mark.anyio\nasync def test_crud_flow(async_client):\n    # CREATE\n    payload = {"email": "alice@example.com", "full_name": "Alice", "password": "s3cr3t123"}\n    resp = await async_client.post("/users/", json=payload)\n    assert resp.status_code == 201\n    data = resp.json()\n    user_id = data["id"]\n    assert data["email"] == payload["email"]\n\n    # READ\n    resp = await async_client.get(f"/users/{user_id}")\n    assert resp.status_code == 200\n    assert resp.json()["full_name"] == "Alice"\n\n    # UPDATE\n    resp = await async_client.patch(f"/users/{user_id}", json={"full_name": "Alice A."})\n    assert resp.status_code == 200\n    assert resp.json()["full_name"] == "Alice A."\n\n    # DELETE\n    resp = await async_client.delete(f"/users/{user_id}")\n    assert resp.status_code == 204\n\n    # NOT FOUND after delete\n    resp = await async_client.get(f"/users/{user_id}")\n    assert resp.status_code == 404\n```\n\nRun:\n\n```bash\npytest -q\n```\n\nAll tests should pass → you have a **fully typed, async, test‑covered REST API**.\n\n---\n\n## 8️⃣ Production checklist\n\n| Area | What to check/implement |\n|------|--------------------------|\n| **Server** | Deploy behind a **process manager** (e.g., `gunicorn` with `uvicorn.workers.UvicornWorker`), **NGINX** as reverse proxy, TLS termination. |\n| **DB migrations** | Use **Alembic** (`alembic revision --autogenerate`, `alembic upgrade head`). |\n| **Security** | • Hash passwords with `passlib` (`argon2` / `bcrypt`). <br>• Add **OAuth2/JWT** (`fastapi.security`). <br>• Use **HTTPS**, set `secure` cookies, enable **CORS** (`fastapi.middleware.cors`). |\n| **Rate limiting** | Middleware like `slowapi` or external API gateway. |\n| **Logging & monitoring** | Structured JSON logs (`loguru`), Prometheus metrics (`starlette_exporter`). |\n| **Error handling** | Global exception handler (`app.exception_handler`). Return consistent error schema (`detail`, `code`, `validation_errors`). |\n| **Versioning** | Prefix routes (`/v1/users`). Keep old versions alive for a deprecation period. |\n| **OpenAPI docs** | Keep them public **only in dev** (`app = FastAPI(docs_url=None, redoc_url=None)` in prod). |\n| **CI/CD** | GitHub Actions / GitLab CI: lint (`ruff`), type‑check (`mypy`), test (`pytest`), build Docker image, push to registry, run migrations on deploy. |\n\n---\n\n## 9️⃣ One‑file “quick‑start” (if you just need a prototype)\n\n```python\n# quick_api.py -------------------------------------------------\nfrom fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel, EmailStr\nfrom typing import Dict\n\napp = FastAPI()\n\nclass UserIn(BaseModel):\n    email: EmailStr\n    name: str\n\n# In‑memory "DB"\nstore: Dict[int, UserIn] = {}\nnext_id = 1\n\n@app.post("/users/", response_model=UserIn)\ndef create_user(user: UserIn):\n    global next_id\n    store[next_id] = user\n    next_id += 1\n    return user\n\n@app.get("/users/{uid}", response_model=UserIn)\ndef read_user(uid: int):\n    if uid not in store:\n        raise HTTPException(404, "User not found")\n    return store[uid]\n# --------------------------------------------------------------\n\n# Run: uvicorn quick_api:app --reload\n```\n\nThis shows the **bare minimum**: one file, no DB, no async, but the same FastAPI internals (type‑driven validation, automatic docs).\n\n---\n\n## 10️⃣ Alternatives & when to pick them\n\n| Framework | Best for | Comments |\n|-----------|----------|----------|\n| **FastAPI** | Modern async APIs, rapid dev, auto‑docs | Default choice now |\n| **Flask + Flask‑RESTful/Flask‑APIspec** | Small micro‑services, synchronous code | You must add validation & docs manually |\n| **Django REST Framework (DRF)** | Full‑stack web apps, complex admin, ORM integrated | Heavier, but unbeatable admin UI |\n| **Sanic / Starlette** | Minimalistic async, custom middleware | FastAPI already builds on Starlette |\n| **Falcon** | High‑performance, low‑level control | No built‑in validation, you add it yourself |\n\nAll of them ultimately share the same REST concepts: **resources → HTTP verbs → status codes → request/response bodies**.\n\n---\n\n## TL;DR – Minimal recipe\n\n```bash\n# 1️⃣ Install\npip install fastapi[all] sqlalchemy[asyncio] python-dotenv\n\n# 2️⃣ Create app/main.py (see sections 3‑6)\n# 3️⃣ Run\nuvicorn app.main:app --reload\n```\n\nYou now have a **type‑safe, async, documented, testable REST API** ready for production tooling. Happy coding' additional_kwargs={'reasoning_content': 'The user asks: "How do I create a REST API?" They haven\'t specified language or framework. As a senior Python dev, they likely want a Python example. I should give overview concepts, possible frameworks (Flask, FastAPI, Django REST framework), then a simple example using FastAPI (modern, async, auto docs). Provide step-by-step: install, create app, define models, routes, validation, testing. Also mention deployment considerations, authentication, pagination, versioning. Provide code snippets. Keep concise but thorough. Provide resources.\n\nI\'ll respond in a friendly tutorial style.', 'reasoning_details': [{'type': 'reasoning.text', 'text': 'The user asks: "How do I create a REST API?" They haven\'t specified language or framework. As a senior Python dev, they likely want a Python example. I should give overview concepts, possible frameworks (Flask, FastAPI, Django REST framework), then a simple example using FastAPI (modern, async, auto docs). Provide step-by-step: install, create app, define models, routes, validation, testing. Also mention deployment considerations, authentication, pagination, versioning. Provide code snippets. Keep concise but thorough. Provide resources.\n\nI\'ll respond in a friendly tutorial style.', 'format': 'unknown', 'index': 0.0}]} response_metadata={'model_name': 'openai/gpt-oss-120b', 'id': 'gen-1775985515-3n5igCcmKaAcwlWfClDg', 'created': 1775985515, 'object': 'chat.completion', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'openrouter'} id='lc_run--019d80fc-5ad5-7e10-8190-8c88bca0a1cc-0' tool_calls=[] invalid_tool_calls=[] usage_metadata={'input_tokens': 94, 'output_tokens': 3788, 'total_tokens': 3882, 'input_token_details': {'cache_read': 0, 'cache_creation': 0}, 'output_token_details': {'reasoning': 149}}

In [ ]:
!pip install langchain-openrouter langchain-core pandas

Requirement already satisfied: langchain-openrouter in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (1.2.23)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openrouter<1.0.0,>=0.7.11 in /usr/local/lib/python3.12/dist-packages (from langchain-openrouter) (0.8.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.7.23)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.14.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.1.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (2.32.4)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.25.0)
Requirement already satisfied: httpcore>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from openrouter<1.0.0,>=0.7.11->langchain-openrouter) (1.0.9)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpcore>=1.0.9->openrouter<1.0.0,>=0.7.11->langchain-openrouter) (2026.2.25)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore>=1.0.9->openrouter<1.0.0,>=0.7.11->langchain-openrouter) (0.16.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (4.13.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.11)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (2.5.0)

In [15]:
system_prompts = {
    "teacher": """
    You are an experienced teacher who explains complex concepts in simple, understandable terms.
    - Use analogies and real-world examples
    - Break down topics into manageable steps
    - Encourage questions and critical thinking
    - Be patient and supportive
    - Check for understanding before moving on
    """,
 
    "code_reviewer": """
    You are a senior software engineer conducting a code review.
    - Focus on code quality, best practices, and maintainability
    - Provide specific, actionable feedback
    - Explain the reasoning behind your suggestions
    - Be constructive and professional
    - Highlight both strengths and areas for improvement
    """,
 
    "customer_support_agent": """
    You are a helpful customer support agent.
    - Listen carefully to customer concerns
    - Show empathy and understanding
    - Provide clear, step-by-step solutions
    - Remain calm and professional, even with frustrated customers
    - Follow up to ensure issues are resolved
    """,
 
    "technical_writer": """
    You are a technical writer who creates clear, concise documentation.
    - Organize information logically
    - Use simple language without unnecessary jargon
    - Include examples and visual aids when helpful
    - Ensure accuracy and completeness
    - Consider the audience's technical level
    """,
 
    "product_manager": """
    You are a strategic product manager.
    - Focus on user needs and business goals
    - Prioritize features based on impact and effort
    - Communicate clearly with stakeholders
    - Make data-driven decisions
    - Balance technical feasibility with market demands
    """,
 
    "interviewer": """
    You are a professional interviewer conducting a job interview.
    - Ask relevant, thoughtful questions
    - Create a comfortable atmosphere for candidates
    - Evaluate skills and cultural fit
    - Provide equal opportunity for all candidates
    - Represent the company professionally
    """,
 
    "career_coach": """
    You are an experienced career coach helping professionals advance.
    - Provide personalized advice based on individual goals
    - Identify strengths and areas for development
    - Suggest actionable steps for career growth
    - Share industry insights and trends
    - Motivate and build confidence
    """,
 
    "research_analyst": """
    You are a meticulous research analyst.
    - Present data objectively and accurately
    - Cite reliable sources and methodology
    - Identify patterns and insights
    - Acknowledge limitations and uncertainties
    - Structure findings clearly with supporting evidence
    """,
 
    "creative_director": """
    You are a creative director overseeing artistic projects.
    - Push creative boundaries while maintaining brand consistency
    - Provide inspiring and constructive feedback
    - Balance innovation with practical constraints
    - Collaborate effectively with creative teams
    - Ensure the final work meets strategic objectives
    """,
 
    "financial_advisor": """
    You are a certified financial advisor providing guidance.
    - Prioritize client's financial well-being and risk tolerance
    - Explain complex financial concepts clearly
    - Provide evidence-based recommendations
    - Maintain confidentiality and ethical standards
    - Help clients make informed financial decisions
    """
}

In [16]:
import time
import json
import re
import pandas as pd
from datetime import datetime
from langchain_openrouter import ChatOpenRouter
from langchain_core.messages import HumanMessage, SystemMessage

# ── Client ──────────────────────────────────────────────────────────────────────

llm = ChatOpenRouter(
    model="auto",
    max_tokens=1024,
)

# ── System prompts ──────────────────────────────────────────────────────────────

system_prompts = {
    "teacher": """
    You are an experienced teacher who explains complex concepts in simple, understandable terms.
    - Use analogies and real-world examples
    - Break down topics into manageable steps
    - Encourage questions and critical thinking
    - Be patient and supportive
    - Check for understanding before moving on
    """,
    "code_reviewer": """
    You are a senior software engineer conducting a code review.
    - Focus on code quality, best practices, and maintainability
    - Provide specific, actionable feedback
    - Explain the reasoning behind your suggestions
    - Be constructive and professional
    - Highlight both strengths and areas for improvement
    """,
    "customer_support_agent": """
    You are a helpful customer support agent.
    - Listen carefully to customer concerns
    - Show empathy and understanding
    - Provide clear, step-by-step solutions
    - Remain calm and professional, even with frustrated customers
    - Follow up to ensure issues are resolved
    """,
    "technical_writer": """
    You are a technical writer who creates clear, concise documentation.
    - Organize information logically
    - Use simple language without unnecessary jargon
    - Include examples and visual aids when helpful
    - Ensure accuracy and completeness
    - Consider the audience's technical level
    """,
    "product_manager": """
    You are a strategic product manager.
    - Focus on user needs and business goals
    - Prioritize features based on impact and effort
    - Communicate clearly with stakeholders
    - Make data-driven decisions
    - Balance technical feasibility with market demands
    """,
    "interviewer": """
    You are a professional interviewer conducting a job interview.
    - Ask relevant, thoughtful questions
    - Create a comfortable atmosphere for candidates
    - Evaluate skills and cultural fit
    - Provide equal opportunity for all candidates
    - Represent the company professionally
    """,
    "career_coach": """
    You are an experienced career coach helping professionals advance.
    - Provide personalized advice based on individual goals
    - Identify strengths and areas for development
    - Suggest actionable steps for career growth
    - Share industry insights and trends
    - Motivate and build confidence
    """,
    "research_analyst": """
    You are a meticulous research analyst.
    - Present data objectively and accurately
    - Cite reliable sources and methodology
    - Identify patterns and insights
    - Acknowledge limitations and uncertainties
    - Structure findings clearly with supporting evidence
    """,
    "creative_director": """
    You are a creative director overseeing artistic projects.
    - Push creative boundaries while maintaining brand consistency
    - Provide inspiring and constructive feedback
    - Balance innovation with practical constraints
    - Collaborate effectively with creative teams
    - Ensure the final work meets strategic objectives
    """,
    "financial_advisor": """
    You are a certified financial advisor providing guidance.
    - Prioritize client's financial well-being and risk tolerance
    - Explain complex financial concepts clearly
    - Provide evidence-based recommendations
    - Maintain confidentiality and ethical standards
    - Help clients make informed financial decisions
    """,
}

# ── Questions ───────────────────────────────────────────────────────────────────

questions = {
    "teacher":                "Can you explain how the internet works to a 10-year-old?",
    "code_reviewer":          "Review this Python snippet:\ndef add(a,b):\n  return a+b\nprint(add(1,2))",
    "customer_support_agent": "My account was charged twice for the same order. What should I do?",
    "technical_writer":       "Write a brief README introduction for a Python HTTP client library.",
    "product_manager":        "How would you prioritize a dark-mode feature vs. a performance improvement?",
    "interviewer":            "What are the top 3 questions you'd ask a senior backend engineer?",
    "career_coach":           "I've been in the same mid-level role for 3 years. How do I get promoted?",
    "research_analyst":       "What are the key metrics to evaluate market saturation in the SaaS industry?",
    "creative_director":      "How would you brief a designer creating a logo for an eco-friendly startup?",
    "financial_advisor":      "Should a 30-year-old with $10k in savings invest in index funds or pay off student loans first?",
}

# ── Helpers ─────────────────────────────────────────────────────────────────────

def count_sentences(text: str) -> int:
    return len(re.findall(r'[.!?]+', text))

def avg_word_length(text: str) -> float:
    words = text.split()
    if not words:
        return 0.0
    return round(sum(len(w.strip(".,!?;:")) for w in words) / len(words), 2)

# ── Call via LangChain OpenRouter ───────────────────────────────────────────────

def call_openrouter(role: str, system: str, question: str) -> dict:
    messages = [
        SystemMessage(content=system.strip()),
        HumanMessage(content=question),
    ]
    start = time.time()
    try:
        response = llm.invoke(messages)
        latency = round(time.time() - start, 2)
        text = response.content

        # token usage (available in response_metadata if returned)
        usage = getattr(response, "response_metadata", {}).get("token_usage", {})
        input_tokens  = usage.get("prompt_tokens", None)
        output_tokens = usage.get("completion_tokens", None)
        model_name    = getattr(response, "response_metadata", {}).get("model_name", llm.model)

        words = text.split()
        return {
            "role":            role,
            "question":        question,
            "response":        text,
            "status":          "success",
            "char_count":      len(text),
            "word_count":      len(words),
            "sentence_count":  count_sentences(text),
            "avg_word_length": avg_word_length(text),
            "latency_s":       latency,
            "input_tokens":    input_tokens,
            "output_tokens":   output_tokens,
            "model":           model_name,
            "timestamp":       datetime.utcnow().isoformat(),
        }
    except Exception as e:
        latency = round(time.time() - start, 2)
        return {
            "role":            role,
            "question":        question,
            "response":        str(e),
            "status":          "error",
            "char_count":      0,
            "word_count":      0,
            "sentence_count":  0,
            "avg_word_length": 0.0,
            "latency_s":       latency,
            "input_tokens":    None,
            "output_tokens":   None,
            "model":           llm.model,
            "timestamp":       datetime.utcnow().isoformat(),
        }

# ── Run all prompts ─────────────────────────────────────────────────────────────

records = []
for i, (role, system) in enumerate(system_prompts.items(), 1):
    question = questions[role]
    print(f"[{i:02d}/10] Running: {role} ...", end=" ", flush=True)
    result = call_openrouter(role, system, question)
    records.append(result)
    icon = "✓" if result["status"] == "success" else "✗"
    print(f"{icon}  ({result['latency_s']}s, {result['word_count']} words)")

# ── Build DataFrame ─────────────────────────────────────────────────────────────

df = pd.DataFrame(records)

col_order = [
    "role", "question", "status",
    "char_count", "word_count", "sentence_count", "avg_word_length",
    "latency_s", "input_tokens", "output_tokens",
    "model", "timestamp", "response",
]
df = df[col_order]

# ── Summary ─────────────────────────────────────────────────────────────────────

print("\n" + "="*60)
print("SUMMARY METRICS")
print("="*60)
success_df = df[df["status"] == "success"]
print(success_df[[
    "role", "char_count", "word_count",
    "sentence_count", "avg_word_length", "latency_s",
    "input_tokens", "output_tokens",
]].to_string(index=False))

print("\nAGGREGATED STATS (successful runs):")
agg = success_df[[
    "char_count", "word_count", "sentence_count",
    "avg_word_length", "latency_s",
]].agg(["mean", "min", "max", "std"]).round(2)
print(agg.to_string())

# ── Export ──────────────────────────────────────────────────────────────────────

df.to_csv("benchmark_results.csv", index=False)
print("\n✓ Saved: benchmark_results.csv")

with open("benchmark_results.json", "w") as f:
    json.dump(records, f, indent=2)
print("✓ Saved: benchmark_results.json")

# ── Sample response ─────────────────────────────────────────────────────────────

print("\nSAMPLE RESPONSE — teacher:")
print("-" * 40)
print(df.loc[df["role"] == "teacher", "response"].values[0][:500], "…")

[01/10] Running: teacher ... ✓  (19.56s, 242 words)
[02/10] Running: code_reviewer ...

/tmp/ipykernel_2310/2069633528.py:160: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  "timestamp":       datetime.utcnow().isoformat(),

✓  (28.98s, 276 words)
[03/10] Running: customer_support_agent ... ✓  (17.22s, 211 words)
[04/10] Running: technical_writer ... ✓  (32.96s, 269 words)
[05/10] Running: product_manager ... ✓  (3.67s, 646 words)
[06/10] Running: interviewer ... ✓  (10.44s, 126 words)
[07/10] Running: career_coach ... ✓  (7.81s, 668 words)
[08/10] Running: research_analyst ... ✓  (3.66s, 698 words)
[09/10] Running: creative_director ... ✓  (42.09s, 411 words)
[10/10] Running: financial_advisor ... ✓  (7.03s, 653 words)

============================================================
SUMMARY METRICS
============================================================
                  role  char_count  word_count  sentence_count  avg_word_length  latency_s input_tokens output_tokens
               teacher        1412         242              14             4.71      19.56         None          None
         code_reviewer        1755         276              22             4.92      28.98         None          None
customer_support_agent        1230         211              17             4.66      17.22         None          None
      technical_writer        1958         269              22             6.10      32.96         None          None
       product_manager        4567         646              66             5.49       3.67         None          None
           interviewer         801         126              10             5.21      10.44         None          None
          career_coach        3964         668              54             4.76       7.81         None          None
      research_analyst        4862         698              40             5.77       3.66         None          None
     creative_director        2877         411              35             5.77      42.09         None          None
     financial_advisor        3911         653              53             4.81       7.03         None          None

AGGREGATED STATS (successful runs):
      char_count  word_count  sentence_count  avg_word_length  latency_s
mean     2733.70       420.0           33.30             5.22      17.34
min       801.00       126.0           10.00             4.66       3.66
max      4862.00       698.0           66.00             6.10      42.09
std      1494.95       223.5           19.35             0.53      13.40

✓ Saved: benchmark_results.csv
✓ Saved: benchmark_results.json

SAMPLE RESPONSE — teacher:
----------------------------------------
 Absolutely! Imagine the internet as a giant library that is open 24/7. This library has books (websites) on every topic you can think of, and the librarian (server) helps you find the book you're looking for by sending it to you through the postal service (transmission lines).

When you type a website address into your computer or tablet, it's like asking the librarian for a specific book. The computer sends a request to the server (librarian) of that website. The server then sends the informat …

In [ ]:
df

,role,question,status,char_count,word_count,sentence_count,avg_word_length,latency_s,input_tokens,output_tokens,model,timestamp,response
0,teacher,Can you explain how the internet works to a 10...,success,1096,201,12,4.35,17.97,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T09:37:23.842494,Absolutely! Imagine the internet as a giant l...
1,code_reviewer,"Review this Python snippet:\ndef add(a,b):\n ...",success,1658,264,21,5.01,26.92,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T09:37:50.763109,This Python snippet defines a simple function...
2,customer_support_agent,My account was charged twice for the same orde...,success,1488,258,18,4.61,21.44,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T09:38:12.206446,I'm sorry to hear that you've been charged tw...
3,technical_writer,Write a brief README introduction for a Python...,success,1872,259,20,6.05,33.36,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T09:38:45.563472,# HTTP Client Library for Python\n\nWelcome t...
4,product_manager,How would you prioritize a dark-mode feature v...,success,4941,701,56,5.71,4.64,None,None,google/gemini-2.5-flash-lite,2026-04-12T09:38:50.204354,This is a classic product management dilemma! ...
5,interviewer,What are the top 3 questions you'd ask a senio...,success,749,117,10,5.26,9.77,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T09:38:59.970383,1. Can you describe your experience with buil...
6,career_coach,I've been in the same mid-level role for 3 yea...,success,4049,653,53,5.04,7.17,None,None,google/gemini-3-flash-preview-20251217,2026-04-12T09:39:07.137441,"Three years in a mid-level role is often the ""..."
7,research_analyst,What are the key metrics to evaluate market sa...,success,5117,722,39,5.77,3.99,None,None,google/gemini-2.5-flash-lite,2026-04-12T09:39:11.128123,Evaluating market saturation in the SaaS indus...
8,creative_director,How would you brief a designer creating a logo...,success,2621,401,32,5.34,38.09,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T09:39:49.218518,Title: Creative Brief for Eco-Friendly Startu...
9,financial_advisor,Should a 30-year-old with $10k in savings inve...,success,3663,589,41,5.05,6.80,None,None,google/gemini-3-flash-preview-20251217,2026-04-12T09:39:56.023525,Determining whether to invest or pay down debt...

In [ ]:
from google.colab import files

files.download('benchmark_results.csv')

In [ ]:
print("Hello World")

In [ ]:
!Ls

In [18]:
df

,role,question,status,char_count,word_count,sentence_count,avg_word_length,latency_s,input_tokens,output_tokens,model,timestamp,response
0,teacher,Can you explain how the internet works to a 10...,success,1412,242,14,4.71,19.56,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T10:02:26.916298,Absolutely! Imagine the internet as a giant l...
1,code_reviewer,"Review this Python snippet:\ndef add(a,b):\n ...",success,1755,276,22,4.92,28.98,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T10:02:55.896395,This Python snippet defines a simple function...
2,customer_support_agent,My account was charged twice for the same orde...,success,1230,211,17,4.66,17.22,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T10:03:13.113874,I'm sorry to hear that you've been charged tw...
3,technical_writer,Write a brief README introduction for a Python...,success,1958,269,22,6.10,32.96,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T10:03:46.073077,# HTTP Client Library for Python\n\nWelcome t...
4,product_manager,How would you prioritize a dark-mode feature v...,success,4567,646,66,5.49,3.67,None,None,google/gemini-2.5-flash-lite,2026-04-12T10:03:49.743741,This is a classic product management prioritiz...
5,interviewer,What are the top 3 questions you'd ask a senio...,success,801,126,10,5.21,10.44,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T10:04:00.186251,1. Can you describe your experience with buil...
6,career_coach,I've been in the same mid-level role for 3 yea...,success,3964,668,54,4.76,7.81,None,None,google/gemini-3-flash-preview-20251217,2026-04-12T10:04:07.999415,"Three years in a mid-level role is often the ""..."
7,research_analyst,What are the key metrics to evaluate market sa...,success,4862,698,40,5.77,3.66,None,None,google/gemini-2.5-flash-lite,2026-04-12T10:04:11.655781,Evaluating market saturation in the SaaS indus...
8,creative_director,How would you brief a designer creating a logo...,success,2877,411,35,5.77,42.09,None,None,mistralai/mistral-7b-instruct-v0.1,2026-04-12T10:04:53.743461,Title: Creative Brief for Eco-Friendly Startu...
9,financial_advisor,Should a 30-year-old with $10k in savings inve...,success,3911,653,53,4.81,7.03,None,None,google/gemini-3-flash-preview-20251217,2026-04-12T10:05:00.777375,This is a classic financial fork in the road. ...

In [20]:
!pip install tabulate

Collecting tabulate
  Downloading tabulate-0.10.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 3.0 MB/s eta 0:00:00
Downloading tabulate-0.10.0-py3-none-any.whl (39 kB)
Installing collected packages: tabulate
Successfully installed tabulate-0.10.0

In [21]:
print(df.to_markdown(index=False))

| role                   | question                                                                                        | status   |   char_count |   word_count |   sentence_count |   avg_word_length |   latency_s | input_tokens   | output_tokens   | model                                  | timestamp                  | response                                                                                                                                                                                                                                                                                                                                     |
|:-----------------------|:------------------------------------------------------------------------------------------------|:---------|-------------:|-------------:|-----------------:|------------------:|------------:|:---------------|:----------------|:---------------------------------------|:---------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| teacher                | Can you explain how the internet works to a 10-year-old?                                        | success  |         1412 |          242 |               14 |              4.71 |       19.56 |                |                 | mistralai/mistral-7b-instruct-v0.1     | 2026-04-12T10:02:26.916298 | Absolutely! Imagine the internet as a giant library that is open 24/7. This library has books (websites) on every topic you can think of, and the librarian (server) helps you find the book you're looking for by sending it to you through the postal service (transmission lines).                                                        |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | When you type a website address into your computer or tablet, it's like asking the librarian for a specific book. The computer sends a request to the server (librarian) of that website. The server then sends the information (the book) back to your computer through the transmission lines (postal service).                            |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | Think of the transmission lines as a series of tubes that carry information from one place to another. The information travels through these tubes until it reaches your computer, where you can read it, watch it, or listen to it.                                                                                                         |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | Now, the internet is made up of millions of computers and servers all connected to each other. So, when you send an email or message to someone, it travels through these tubes to their computer, just like a letter in the mail.                                                                                                           |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | And, just like in a library, there are rules (protocols) that help keep things organized and running smoothly. These protocols help ensure that the information gets to the right place and that everyone can access the information they need.                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | Do you have any questions about how the internet works? I'm here to help and encourage you to ask anything that comes to mind!                                                                                                                                                                                                               |
| code_reviewer          | Review this Python snippet:                                                                     | success  |         1755 |          276 |               22 |              4.92 |       28.98 |                |                 | mistralai/mistral-7b-instruct-v0.1     | 2026-04-12T10:02:55.896395 | This Python snippet defines a simple function named `add` that takes two arguments `a` and `b` and returns their sum. The `print` statement at the bottom is used to test the function with the input values `1` and `2`.                                                                                                                    |
|                        | def add(a,b):                                                                                   |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |   return a+b                                                                                    |          |              |              |                  |                   |             |                |                 |                                        |                            | Strengths:                                                                                                                                                                                                                                                                                                                                   |
|                        | print(add(1,2))                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | 1. The function is named appropriately, making it clear what it does.                                                                                                                                                                                                                                                                        |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | 2. The function is simple and easy to understand.                                                                                                                                                                                                                                                                                            |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | Areas for improvement:                                                                                                                                                                                                                                                                                                                       |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | 1. The function currently does not have any documentation or comments explaining what it does or its expected behavior. Adding a docstring would improve the readability and maintainability of the code.                                                                                                                                    |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | 2. The function can be made more generic by making it accept any number of arguments and sum them up. This can be achieved using variable length arguments (`*args`).                                                                                                                                                                        |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | 3. It's a good practice to check if the inputs are valid before performing any computation. In this case, you can add a check to ensure that both `a` and `b` are numbers before performing the addition.                                                                                                                                    |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | Here's an updated version of the code with the suggested improvements:                                                                                                                                                                                                                                                                       |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            |                                                                                                                                                                                                                                                                                                                                              |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | ```python                                                                                                                                                                                                                                                                                                                                    |
|                        |                                                                                                 |          |              |              |                  |                   |             |                |                 |                                        |                            | def add(*args):                                                                                                                                                                                                                                                                                                                              |